### ISSUE TITLE
Progress bar display problem

### ISSUE THREAD

**Issue by geekya215** [theme-next/theme-next-reading-progress#1]
- For a shorter article, the progress bar does not correctly correspond to the progress.(can not be loaded to 100%)
- After entering the article for the first time, the progress bar can be loaded from the leftmost end normally. If you roll back to the beginning of the article again, the progress bar will have a distance from the left end.(can not be loaded from 0%)

**Comment by maple3142** [comment]
It has been fixed in f1dcdfc585f60cb1614c480c3b06a1632b1b6d8e.
